# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require File.join(File.dirname(__FILE__), '../app/', 'app.rb')
require 'rspec'
require 'capybara/rspec'
require 'capybara/dsl'
require 'rack/test'

ENV['RACK_ENV'] = 'test'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = false
  config.run_all_when_everything_filtered = false

  config.include Rack::Test::Methods
  config.include Capybara::DSL

  Capybara.app = KayochinGohan::App

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
